# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

@sum = 0
ENDS_AT = 4000000

def even_sum_fib(f, s)
  @sum += f if f % 2 == 0
  even_sum_fib(s, f+s) if s <= ENDS_AT
end

even_sum_fib(1, 2)
puts @sum