/* *Even Fibonacci numbers*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

package main

import (
	"common"
	"fmt"
)

var max uint32 = 4000000

func main() {
	out := make(chan uint32)
	go common.Fibonacci(uint32(1), uint32(2), max, out)
	var sum uint32
	for n := range out {
		if n%2 == 0 {
			sum += n
		}
	}
	fmt.Println("Sum: ", sum)
}
